[package]
name = "speki-web"
version = "0.1.0"
authors = ["tor <tor.saebjornsen@cognite.com>"]
edition = "2021"

[dependencies]

#dioxus = { version = "0.6.0-alpha.5", features = ["web", "router"] }
dioxus = { git = "https://github.com/DioxusLabs/dioxus.git", features = [
    "router",
    "web",
] }

dioxus-logger.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
wasm-bindgen.workspace = true
tracing-tree.workspace = true
futures.workspace = true
futures-util.workspace = true
gloo.workspace = true
gloo-net.workspace = true
gloo-timers.workspace = true
gloo-utils.workspace = true
js-sys.workspace = true
serde.workspace = true
serde-wasm-bindgen.workspace = true
serde_json.workspace = true
wasm-bindgen-futures.workspace = true
wasm-cookies.workspace = true
web-sys.workspace = true
toml.workspace = true
async-trait.workspace = true
async-lock.workspace = true
uuid.workspace = true
manganis.workspace = true
time.workspace = true

speki-dto = { path = "../speki-dto" }
speki-core = { path = "../speki-core" }
speki-idb = { path = "../speki-idb" }
