[package]
name = "speki-web"
version = "0.1.0"
authors = ["tor <tor.saebjornsen@cognite.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

dioxus = { version = "0.5", features = ["web", "router"] }

# Debug
dioxus-logger = "0.5.1"
futures = "0.3.31"
futures-util = "0.3"
gloo = "0.11.0"
gloo-timers = { version = "0.3", features = ["futures"] }
gloo-utils = "0.2.0"
js-sys = "0.3.72"
serde = "1.0.214"
serde-wasm-bindgen = "0.6.5"
serde_json = "1.0.132"
wasm-bindgen = "0.2.95"
wasm-bindgen-futures = "0.4.45"
wasm-cookies = "0.2.1"
web-sys = "0.3.72"
