[package]
name = "speki-dto"
version = "0.1.0"
edition = "2021"

[dependencies]
serde.workspace = true
dirs.workspace = true
gkquad.workspace = true
serde_json.workspace = true
tokio.workspace = true
toml.workspace = true
uuid.workspace = true
omtrent.workspace = true
