[package]
name = "speki-dto"
version = "0.1.0"
edition = "2021"

[dependencies]
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
omtrent.workspace = true
futures.workspace = true
async-trait = "0.1.83"
