[package]
name = "speki-fs"
version = "0.1.0"
edition = "2021"

[dependencies]
speki-dto.workspace = true
rayon.workspace = true
toml.workspace = true
serde.workspace = true
dirs.workspace = true
async-trait.workspace = true
