cargo-features = ["edition2024"]

[package]
name = "simpletime"
version = "0.1.0"
edition = "2024"
authors = ["tor torberge@outlook.com"]
description = "simple timer macro"
license = "GPL-2.0-only"

[lib]
proc-macro = false

[dependencies]
