name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Dioxus Build
        uses: actions/cache@v3
        with:
          path: |
            ./target
            ./speki-web/.cargo/registry
            ./speki-web/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Cache Docker Layers
        uses: actions/cache@v3
        with:
          path: /tmp/.docker-cache
          key: ${{ runner.os }}-docker-${{ hashFiles('Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Use Docker to Build with Dioxus CLI
        env:
          DOCKER_CACHE_DIR: /tmp/.docker-cache
        run: |
          mkdir -p $DOCKER_CACHE_DIR
          docker load < $DOCKER_CACHE_DIR/cached_image.tar || echo "No cache available"
          docker pull nigeleke/docker-dioxus-cli:v0.6.1 || true
          docker save nigeleke/docker-dioxus-cli:v0.6.1 > $DOCKER_CACHE_DIR/cached_image.tar
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -v ${{ github.workspace }}/target:/workspace/target \
            -v ${{ github.workspace }}/speki-web/.cargo:/workspace/speki-web/.cargo \
            -w /workspace/speki-web \
            nigeleke/docker-dioxus-cli:v0.6.1 \
            dx build --release

      - name: Verify Firebase Config and Build Output
        continue-on-error: true
        run: |
          echo "Checking firebase.json:"
          cat firebase.json || echo "firebase.json not found!"
          echo "Checking build output directory:"
          ls -lah target/dx/speki-web/release/web/public || echo "Build output directory not found!"
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SPEKI_72569 }}
          channelId: live
          projectId: speki-72569
