name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Cargo
        uses: actions/cache@v3
        with:
          path: |
            ./speki-web/target
            ./speki-web/.cargo/registry
            ./speki-web/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Use Docker to Build with Dioxus CLI
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -v /workspace/speki-web/target:/workspace/speki-web/target \
            -v /workspace/speki-web/.cargo:/workspace/speki-web/.cargo \
            -w /workspace/speki-web \
            nigeleke/docker-dioxus-cli:v0.6.1 \
            dx build --release

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SPEKI_72569 }}
          channelId: live
          projectId: speki-72569

